name: Docker Image CI for GHCR
on:
    push
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit tests
              run: npm test
            - name: Build and push the image
              run:  |
                docker login --username bindubheesetty --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/bindubheesetty/arithmetic-service:1 --file Dockerfile .
                docker push ghcr.io/bindubheesetty/arithmetic-service:1
            - name: Publish the image to Azure container registry
              run: |
                docker login --username practicum16cr --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum16bibhee.azurecr.io
                docker build -t ghcr.io/bindubheesetty/arithmetic-service:1 practicum16bibhee.azurecr.io/arithmetic-service:1
                docker push practicum16bibhee.azurecr.io/arithmetic-service:1
                


# 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
# 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
