name: Docker Image CI for GHCR
on:
    push
jobs:
    build_and_publish:
        runs_on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run:  |
                docker login --username BinduBheesetty --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/BinduBheesetty/arithmetic-service:latest --file Dockerfile .
                docker push ghcr.io/BinduBheesetty/arithmetic-service:latest
